name = "Nitpack"
author = "nint8835"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0036f6f52bd0e4c4b2f63b2dfa19f1d2c41983e6c447e6e985fef97f9795a43"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
