name = "Nitpack"
author = "nint8835"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdd25304e4d6d238c5ecfd2a4134eeb369e72a3ebd8b666794359cc68368883d"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
